name: Build and deploy ASP.Net Core app to Azure Web App - testmmmm(devv)

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Récupérer le code du dépôt GitHub
      - uses: actions/checkout@v4

      # Installer le SDK .NET
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Restaurer les dépendances du projet .NET
      - name: Restore dependencies
        run: dotnet restore ./HelloWorldApp.csproj

      # Compiler le projet avec configuration "Release"
      - name: Build with dotnet
        run: dotnet build ./HelloWorldApp.csproj --configuration Release

      # Publier l'application
      - name: dotnet publish
        run: dotnet publish ./HelloWorldApp.csproj -c Release -o ./myapp

      # Télécharger l'artefact pour le job de déploiement
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@
