name: Build and deploy ASP.Net Core app to Azure Web App - testmmmm(devv)

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Récupérer le code du dépôt GitHub
      - uses: actions/checkout@v4

      # Installer le SDK .NET
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Restaurer les dépendances du projet .NET
      - name: Restore dependencies
        run: dotnet restore ./HelloWorldApp/HelloWorldApp.csproj

      # Compiler le projet avec configuration "Release"
      - name: Build with dotnet
        run: dotnet build ./HelloWorldApp/HelloWorldApp.csproj --configuration Release

      # Publier l'application
      - name: dotnet publish
        run: dotnet publish ./HelloWorldApp/HelloWorldApp.csproj -c Release -o ./myapp

      # Télécharger l'artefact pour le job de déploiement
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'devv'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Ceci est requis pour demander le JWT

    steps:
      # Télécharger l'artefact créé dans le job de build
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      # Se connecter à Azure avec les identifiants secrets
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      # Déployer l'application sur Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'testmmmm'
          slot-name: 'devv'
          package: ./myapp
