name: Build and deploy ASP.Net Core app to Azure Web App - testmmmm(devv)

on:
  push:
    branches:
      - dev  # Déclenchement lors d'un push sur la branche dev
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Étape 1 : Cloner le dépôt GitHub
      - uses: actions/checkout@v4

      # Étape 2 : Configurer le SDK .NET Core
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Étape 3 : Afficher le contenu du répertoire (pour vérifier la structure des fichiers)
      - name: Afficher le contenu du répertoire
        run: dir

      # Étape 4 : Compiler l'application
      - name: Build with dotnet
        run: dotnet build --configuration Release

      # Étape 5 : Publier l'application
      - name: dotnet publish
        run: dotnet publish -c Release -o ./myapp

      # Étape 6 : Télécharger l'artefact pour le job de déploiement
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'devv'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Ceci est requis pour demander le JWT

    steps:
      # Étape 7 : Télécharger l'artefact du job de build
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      # Étape 8 : Se connecter à Azure avec les secrets GitHub
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # Étape 9 : Déployer l'application sur Azure Web App dans le slot devv
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'testmmmm'  # Nom de votre application Web
          slot-name: 'devv'     # Nom du slot dans lequel vous déployez
          package: ./myapp
